baseURL: "https://beatrice-portelli.github.io/eqai-hugobricks"
# baseURL: "/"
relativeURLs: true 
theme: hugobricks
defaultContentLanguage: eqai-2025
defaultContentLanguageInSubdir: true
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  eqai-2025:
    languageName: EQAI 2025
    contentDir: content/main
    weight: 2
    disabled: false
  eqai-2024:
    languageName: EQAI 2024
    contentDir: content/main
    weight: 3
    disabled: false
  eqai-2023:
    languageName: EQAI 2023
    contentDir: content/main
    weight: 4
    disabled: false
  eqai-2022:
    languageName: EQAI 2022
    contentDir: content/main
    weight: 5
    disabled: false
